language: java
jdk:
  - oraclejdk11

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# Alert on Mail when CI executed
notifications:
  email:
    recipients:
      - iamyoursea0@gmail.com
