cloud:
  aws:
    credentials:
      instanceProfile: true
    s3:
      bucket: sey-community-files
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB